import 'package:flutter/foundation.dart';

/// Multi-language provider for the entire app UI.
/// Supports 10 Indian languages + English.
class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'English';

  String get currentLanguage => _currentLanguage;

  void setLanguage(String lang) {
    if (lang != _currentLanguage && _translations.containsKey(lang)) {
      _currentLanguage = lang;
      notifyListeners();
    }
  }

  /// Translate a key to the current language.
  /// Falls back to English if key not found.
  String tr(String key) {
    final langMap = _translations[_currentLanguage];
    if (langMap != null && langMap.containsKey(key)) {
      return langMap[key]!;
    }
    // Fallback to English
    return _translations['English']?[key] ?? key;
  }

  static const List<String> supportedLanguages = [
    'English',
    'Hindi',
    'Hinglish',
    'Marathi',
    'Tamil',
    'Telugu',
    'Bengali',
    'Kannada',
    'Gujarati',
    'Punjabi',
  ];

  static const Map<String, String> languageEmojis = {
    'English': '🇬🇧',
    'Hindi': '🇮🇳',
    'Hinglish': '🔀',
    'Marathi': '🏵️',
    'Tamil': '🎭',
    'Telugu': '🌺',
    'Bengali': '🐅',
    'Kannada': '🏛️',
    'Gujarati': '🦁',
    'Punjabi': '🌾',
  };

  // ═══════════════════════════════════════════════════════════════════════════
  // TRANSLATIONS MAP
  // ═══════════════════════════════════════════════════════════════════════════

  static const Map<String, Map<String, String>> _translations = {
    // ── English ────────────────────────────────────────────────────────────
    'English': {
      // Navigation
      'nav_home': 'Home',
      'nav_history': 'History',
      'nav_mandi': 'Mandi',
      'nav_profile': 'Profile',
      'nav_godown': 'Godown',

      // Mandi Hub
      'mandi_hub': 'Mandi Hub',
      'tab_prices': '📊 Prices',
      'tab_ai_chat': '🤖 AI Chat',
      'tab_bargain': '🤝 Bargain',
      'chat_in': 'Chat in',
      'clear': 'Clear',
      'ask_placeholder': 'Ask about prices, tips, storage...',
      'thinking': 'Thinking...',
      'ai_assistant': 'AI Market Assistant',
      'ai_subtitle': 'Ask about prices, quality, storage,\nnegotiation tips — in any language!',
      'updated': 'Updated',
      'fetching': 'Fetching...',
      'items': 'items',
      'search_placeholder': 'Search market, crop, district...',
      'no_prices': 'No prices found',
      'retry': 'Retry',
      'fetching_prices': 'Fetching live mandi prices...',

      // Godown / Storage
      'godown_title': '🏭 Smart Godown',
      'godown_subtitle': 'AI-powered crop storage advisor',
      'select_crop': 'Select Crop',
      'enter_crop': 'Enter crop name...',
      'storage_advice': 'Storage Advice',
      'weather_status': 'Weather Status',
      'safe_locations': 'Safe Storage Locations',
      'ideal_temp': 'Ideal Temperature',
      'ideal_humidity': 'Ideal Humidity',
      'shelf_life': 'Shelf Life',
      'current_weather': 'Current Weather',
      'storage_risk': 'Storage Risk',
      'risk_low': 'Low Risk ✅',
      'risk_medium': 'Medium Risk ⚠️',
      'risk_high': 'High Risk 🔴',
      'get_advice': 'Get Storage Advice',
      'loading_advice': 'Analyzing weather & storage...',
      'godown_locations': 'Nearby Godown Locations',
      'weather_crop_check': 'Weather-Crop Check',
      'crop_safe': 'Safe to store',
      'crop_caution': 'Store with caution',
      'crop_danger': 'Not ideal for storage',

      // Weather
      'weather': 'Weather',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'wind': 'Wind',

      // Profile
      'language': 'Language',
      'select_language': 'Select Language',
      'settings': 'Settings',

      // Harvest Prediction
      'nav_harvest': 'Harvest',
      'harvest_title': 'Harvest Prediction',
      'harvest_subtitle': 'AI predicts your optimal harvest window using weather, crop maturity & price trends',
      'predict_harvest': 'Predict Best Harvest Window',
      'predicting': 'Analyzing...',
      'best_harvest_window': 'Best Harvest Window',
      'confidence': 'Confidence',
      'day_by_day_scores': '10-Day Harvest Score',
      'score_explanation': 'Each day scored on rain, temperature, wind & price trend',
      'ai_harvest_advice': 'AI Harvest Advisor',
      'crop_maturity_info': 'Crop Maturity Info',
      'crop': 'Crop',
      'crop_type': 'Crop Type',
      'maturity_range': 'Maturity Range',
      'rain_tolerance': 'Rain Tolerance',
      'sow_date': 'Sow Date',
      'expected_harvest': 'Expected Harvest',
      'maturity_days_hint': 'Custom maturity days (optional)',
      'city': 'City / Location',
      'excellent': 'Excellent',
      'fair': 'Fair',
      'poor': 'Poor',
      'best_window': 'Best Window',

      // Market Recommendation
      'nav_best_market': 'Best Mkt',
      'market_rec_title': 'Best Market Finder',
      'market_rec_subtitle': 'AI finds the most profitable market for your crop — factoring in net price, travel cost, volatility & competition',
      'select_crop_to_sell': 'Select Crop to Sell',
      'your_location': 'Your Location',
      'find_best_market': 'Find Best Market 🎯',
      'analyzing': 'Analyzing Markets...',
      'recommended_market': 'Recommended Market',
      'expected_net': 'Expected Net Profit',
      'modal_price': 'Modal Price',
      'travel': 'Travel',
      'volatility': 'Volatility',
      'ai_market_advice': 'AI Market Advisor',
      'score_breakdown': 'Score Breakdown',
      'overall_score': 'Overall Score',
      'net_price_score': 'Net Price',
      'regional_advantage': 'Regional Advantage',
      'price_stability': 'Price Stability',
      'low_competition': 'Low Competition',
      'all_markets_ranked': 'All Markets Ranked',
      'ranked_explanation': 'Scored on net price (40%), regional advantage (25%), stability (20%), competition (15%)',
      'net': 'Net',
      'modal': 'Modal',
      'vol': 'Vol',

      // Spoilage Prevention Ranking
      'preservation_ranking': 'Spoilage Prevention Ranking',
      'preservation_subtitle': 'Actions ranked by cost-effectiveness — best value first',
      'action': 'Action',
      'cost_col': 'Cost',
      'effectiveness': 'Effect %',
      'low_cost': 'Low cost',
      'medium_cost': 'Medium',
      'high_cost': 'High cost',

      // Explainability Panel
      'why_harvest_now': 'Why Harvest Now?',
      'why_this_market': 'Why This Market?',
      'explainability_subtitle': 'Structured data-driven reasoning',
      'supporting_factors': 'Supporting Factors',
      'risk_factors': 'Risk Factors',
      'low_rain_window': 'Low Rainfall Window',
      'rain_risk': 'Rain Risk Alert',
      'temp_suitable': 'Temperature Suitable',
      'extreme_heat': 'Extreme Heat Warning',
      'calm_wind': 'Calm Wind Conditions',
      'high_wind': 'High Wind Risk',
      'rain_after_window': 'Rain Expected After Window',
      'price_rising': 'Price Trend Rising',
      'price_falling': 'Price Trend Falling',
      'price_advantage': 'Price Advantage',
      'transit_factor': 'Transit Factor',

      // Transit Time Risk
      'transit_risk': 'Transit Time Risk',
      'transit_time': 'Transit Time',
      'perishable': 'Perishable',
      'non_perishable': 'Non-perishable',
      'est_spoilage': 'Est. Spoilage',
      'spoilage_risk': 'Spoilage Risk',
      'high_spoilage_warning': 'High spoilage risk! Consider cold transport or sell to a closer market.',

      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'ok': 'OK',
      'cancel': 'Cancel',
      'refresh': 'Refresh',
    },

    // ── Hindi ──────────────────────────────────────────────────────────────
    'Hindi': {
      'nav_home': 'होम',
      'nav_history': 'इतिहास',
      'nav_mandi': 'मंडी',
      'nav_profile': 'प्रोफ़ाइल',
      'nav_godown': 'गोदाम',
      'mandi_hub': 'मंडी हब',
      'tab_prices': '📊 भाव',
      'tab_ai_chat': '🤖 AI चैट',
      'tab_bargain': '🤝 मोल-भाव',
      'chat_in': 'भाषा',
      'clear': 'साफ़ करें',
      'ask_placeholder': 'भाव, सुझाव, भंडारण के बारे में पूछें...',
      'thinking': 'सोच रहा हूँ...',
      'ai_assistant': 'AI बाज़ार सहायक',
      'ai_subtitle': 'भाव, गुणवत्ता, भंडारण,\nमोल-भाव सुझाव पूछें — किसी भी भाषा में!',
      'updated': 'अपडेट',
      'fetching': 'लोड हो रहा...',
      'items': 'आइटम',
      'search_placeholder': '🔍 बाज़ार, फसल, जिला खोजें...',
      'no_prices': 'कोई भाव नहीं मिला',
      'retry': 'फिर कोशिश करें',
      'fetching_prices': 'लाइव मंडी भाव लोड हो रहे हैं...',
      'godown_title': '🏭 स्मार्ट गोदाम',
      'godown_subtitle': 'AI फसल भंडारण सलाहकार',
      'select_crop': 'फसल चुनें',
      'enter_crop': 'फसल का नाम लिखें...',
      'storage_advice': 'भंडारण सलाह',
      'weather_status': 'मौसम स्थिति',
      'safe_locations': 'सुरक्षित भंडारण स्थान',
      'ideal_temp': 'आदर्श तापमान',
      'ideal_humidity': 'आदर्श नमी',
      'shelf_life': 'शेल्फ लाइफ',
      'current_weather': 'वर्तमान मौसम',
      'storage_risk': 'भंडारण जोखिम',
      'risk_low': 'कम जोखिम ✅',
      'risk_medium': 'मध्यम जोखिम ⚠️',
      'risk_high': 'उच्च जोखिम 🔴',
      'get_advice': 'भंडारण सलाह लें',
      'loading_advice': 'मौसम और भंडारण विश्लेषण...',
      'godown_locations': 'नज़दीकी गोदाम स्थान',
      'weather_crop_check': 'मौसम-फसल जाँच',
      'crop_safe': 'भंडारण के लिए सुरक्षित',
      'crop_caution': 'सावधानी से भंडारण करें',
      'crop_danger': 'भंडारण के लिए उचित नहीं',
      'weather': 'मौसम',
      'temperature': 'तापमान',
      'humidity': 'नमी',
      'wind': 'हवा',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'settings': 'सेटिंग्स',
      // Harvest
      'nav_harvest': 'कटाई',
      'harvest_title': 'कटाई भविष्यवाणी',
      'harvest_subtitle': 'AI मौसम, फसल परिपक्वता और भाव के आधार पर सबसे अच्छा कटाई समय बताता है',
      'predict_harvest': 'कटाई का सही समय जानें',
      'predicting': 'विश्लेषण हो रहा...',
      'best_harvest_window': 'सर्वश्रेष्ठ कटाई समय',
      'confidence': 'विश्वसनीयता',
      'day_by_day_scores': '10 दिन का कटाई स्कोर',
      'score_explanation': 'हर दिन बारिश, तापमान, हवा और भाव ट्रेंड पर स्कोर',
      'ai_harvest_advice': 'AI कटाई सलाहकार',
      'crop_maturity_info': 'फसल परिपक्वता जानकारी',
      'crop': 'फसल',
      'crop_type': 'फसल प्रकार',
      'maturity_range': 'परिपक्वता अवधि',
      'rain_tolerance': 'बारिश सहनशीलता',
      'sow_date': 'बुवाई तिथि',
      'expected_harvest': 'अपेक्षित कटाई',
      'maturity_days_hint': 'कस्टम परिपक्वता दिन (वैकल्पिक)',
      'city': 'शहर / स्थान',
      'excellent': 'उत्तम',
      'fair': 'ठीक',
      'poor': 'खराब',
      'best_window': 'बेस्ट विंडो',

      // Market Recommendation
      'nav_best_market': 'बेस्ट मार्केट',
      'market_rec_title': 'सबसे अच्छा बाज़ार',
      'market_rec_subtitle': 'AI आपकी फसल के लिए सबसे फायदेमंद मंडी ढूंढता है — भाव, ट्रांसपोर्ट, उतार-चढ़ाव और प्रतिस्पर्धा को ध्यान में रखकर',
      'select_crop_to_sell': 'बेचने के लिए फसल चुनें',
      'your_location': 'आपका स्थान',
      'find_best_market': 'सबसे अच्छा बाज़ार खोजें 🎯',
      'analyzing': 'बाज़ार विश्लेषण...',
      'recommended_market': 'अनुशंसित बाज़ार',
      'expected_net': 'अपेक्षित शुद्ध लाभ',
      'modal_price': 'मोडल भाव',
      'travel': 'ट्रांसपोर्ट',
      'volatility': 'उतार-चढ़ाव',
      'ai_market_advice': 'AI बाज़ार सलाहकार',
      'score_breakdown': 'स्कोर विवरण',
      'overall_score': 'कुल स्कोर',
      'net_price_score': 'शुद्ध भाव',
      'regional_advantage': 'क्षेत्रीय लाभ',
      'price_stability': 'भाव स्थिरता',
      'low_competition': 'कम प्रतिस्पर्धा',
      'all_markets_ranked': 'सभी मंडियाँ (रैंक)',
      'ranked_explanation': 'शुद्ध भाव (40%), क्षेत्रीय लाभ (25%), स्थिरता (20%), प्रतिस्पर्धा (15%) पर स्कोर',
      'net': 'शुद्ध',
      'modal': 'मोडल',
      'vol': 'उतार',

      // Spoilage Prevention
      'preservation_ranking': 'खराबी रोकथाम रैंकिंग',
      'preservation_subtitle': 'लागत-प्रभावशीलता के अनुसार क्रमबद्ध — सबसे अच्छा पहले',
      'action': 'कार्रवाई',
      'cost_col': 'लागत',
      'effectiveness': 'प्रभाव %',
      'low_cost': 'कम लागत',
      'medium_cost': 'मध्यम',
      'high_cost': 'अधिक लागत',

      // Explainability
      'why_harvest_now': 'अभी कटाई क्यों?',
      'why_this_market': 'यह बाज़ार क्यों?',
      'explainability_subtitle': 'डेटा-आधारित संरचित तर्क',
      'supporting_factors': 'सहायक कारक',
      'risk_factors': 'जोखिम कारक',
      'low_rain_window': 'कम बारिश अवधि',
      'rain_risk': 'बारिश जोखिम चेतावनी',
      'temp_suitable': 'तापमान उपयुक्त',
      'extreme_heat': 'अत्यधिक गर्मी चेतावनी',
      'calm_wind': 'शांत हवा',
      'high_wind': 'तेज़ हवा जोखिम',
      'rain_after_window': 'विंडो के बाद बारिश अपेक्षित',
      'price_rising': 'भाव बढ़ रहे हैं',
      'price_falling': 'भाव गिर रहे हैं',
      'price_advantage': 'भाव लाभ',
      'transit_factor': 'ट्रांसपोर्ट कारक',

      // Transit Risk
      'transit_risk': 'ट्रांसपोर्ट समय जोखिम',
      'transit_time': 'ट्रांसपोर्ट समय',
      'perishable': 'जल्दी खराब होने वाली',
      'non_perishable': 'टिकाऊ',
      'est_spoilage': 'अनुमानित हानि',
      'spoilage_risk': 'खराबी जोखिम',
      'high_spoilage_warning': 'खराबी जोखिम अधिक! कोल्ड ट्रांसपोर्ट या नज़दीकी मंडी चुनें।',

      'loading': 'लोड हो रहा...',
      'error': 'त्रुटि',
      'ok': 'ठीक',
      'cancel': 'रद्द करें',
      'refresh': 'रिफ्रेश',
    },

    // ── Hinglish ───────────────────────────────────────────────────────────
    'Hinglish': {
      'nav_home': 'Home',
      'nav_history': 'History',
      'nav_mandi': 'Mandi',
      'nav_profile': 'Profile',
      'nav_godown': 'Godown',
      'mandi_hub': 'Mandi Hub',
      'tab_prices': '📊 Prices',
      'tab_ai_chat': '🤖 AI Chat',
      'tab_bargain': '🤝 Bargain',
      'chat_in': 'Chat in',
      'clear': 'Clear',
      'ask_placeholder': 'Rate, tips, storage ke baare mein pucho...',
      'thinking': 'Soch raha hai...',
      'ai_assistant': 'AI Market Assistant',
      'ai_subtitle': 'Rate, quality, storage, bargaining\ntips pucho — kisi bhi bhasha mein!',
      'updated': 'Updated',
      'fetching': 'Fetching...',
      'items': 'items',
      'search_placeholder': '🔍 Market, fasal, district search karo...',
      'no_prices': 'Koi rate nahi mila',
      'retry': 'Phir try karo',
      'fetching_prices': 'Live mandi rates aa rahe hain...',
      'godown_title': '🏭 Smart Godown',
      'godown_subtitle': 'AI fasal storage advisor',
      'select_crop': 'Fasal chuno',
      'enter_crop': 'Fasal ka naam likho...',
      'storage_advice': 'Storage Advice',
      'weather_status': 'Weather Status',
      'safe_locations': 'Safe Storage Locations',
      'ideal_temp': 'Ideal Temperature',
      'ideal_humidity': 'Ideal Humidity',
      'shelf_life': 'Shelf Life',
      'current_weather': 'Abhi ka Weather',
      'storage_risk': 'Storage Risk',
      'risk_low': 'Kam Risk ✅',
      'risk_medium': 'Thoda Risk ⚠️',
      'risk_high': 'Zyada Risk 🔴',
      'get_advice': 'Storage Advice Lo',
      'loading_advice': 'Weather & storage check ho raha...',
      'godown_locations': 'Paas ke Godown',
      'weather_crop_check': 'Weather-Fasal Check',
      'crop_safe': 'Store karna safe hai',
      'crop_caution': 'Dhyaan se store karo',
      'crop_danger': 'Store karna sahi nahi',
      'weather': 'Mausam',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'wind': 'Hawa',
      'language': 'Bhasha',
      'select_language': 'Bhasha Chuno',
      'settings': 'Settings',
      // Harvest
      'nav_harvest': 'Harvest',
      'harvest_title': 'Harvest Prediction',
      'harvest_subtitle': 'AI weather, fasal maturity aur price trend se best harvesting time batata hai',
      'predict_harvest': 'Best Harvest Time Jaano',
      'predicting': 'Analyze ho raha hai...',
      'best_harvest_window': 'Best Harvest Window',
      'confidence': 'Confidence',
      'day_by_day_scores': '10-Din ka Harvest Score',
      'score_explanation': 'Har din rain, temp, wind aur price trend pe score',
      'ai_harvest_advice': 'AI Harvest Advisor',
      'crop_maturity_info': 'Fasal Maturity Info',
      'crop': 'Fasal',
      'crop_type': 'Fasal Type',
      'maturity_range': 'Maturity Range',
      'rain_tolerance': 'Rain Sahansheelta',
      'sow_date': 'Buvai Date',
      'expected_harvest': 'Expected Harvest',
      'maturity_days_hint': 'Custom maturity days (optional)',
      'city': 'City / Location',
      'excellent': 'Excellent',
      'fair': 'Theek',
      'poor': 'Kharab',
      'best_window': 'Best Window',

      // Market Recommendation
      'nav_best_market': 'Best Mkt',
      'market_rec_title': 'Best Market Finder',
      'market_rec_subtitle': 'AI tumhari fasal ke liye sabse profitable mandi dhundhta hai — net price, transport, volatility aur competition dekh ke',
      'select_crop_to_sell': 'Bechne ke liye Fasal Chuno',
      'your_location': 'Tumhara Location',
      'find_best_market': 'Best Market Dhundho 🎯',
      'analyzing': 'Markets Analyze ho rahe...',
      'recommended_market': 'Recommended Market',
      'expected_net': 'Expected Net Profit',
      'modal_price': 'Modal Price',
      'travel': 'Travel',
      'volatility': 'Volatility',
      'ai_market_advice': 'AI Market Advisor',
      'score_breakdown': 'Score Breakdown',
      'overall_score': 'Overall Score',
      'net_price_score': 'Net Price',
      'regional_advantage': 'Regional Advantage',
      'price_stability': 'Price Stability',
      'low_competition': 'Low Competition',
      'all_markets_ranked': 'Sab Markets Ranked',
      'ranked_explanation': 'Net price (40%), regional advantage (25%), stability (20%), competition (15%) pe score',
      'net': 'Net',
      'modal': 'Modal',
      'vol': 'Vol',

      // Spoilage Prevention
      'preservation_ranking': 'Spoilage Prevention Ranking',
      'preservation_subtitle': 'Cost-effectiveness ke hisaab se ranked — sabse achha pehle',
      'action': 'Action',
      'cost_col': 'Cost',
      'effectiveness': 'Effect %',
      'low_cost': 'Kam cost',
      'medium_cost': 'Medium',
      'high_cost': 'Zyada cost',

      // Explainability
      'why_harvest_now': 'Abhi Harvest Kyun?',
      'why_this_market': 'Ye Market Kyun?',
      'explainability_subtitle': 'Data-driven structured reasoning',
      'supporting_factors': 'Supporting Factors',
      'risk_factors': 'Risk Factors',
      'low_rain_window': 'Kam Baarish Window',
      'rain_risk': 'Baarish Risk Alert',
      'temp_suitable': 'Temperature Sahi Hai',
      'extreme_heat': 'Bohot Garmi Warning',
      'calm_wind': 'Hawa Shaant Hai',
      'high_wind': 'Tez Hawa Risk',
      'rain_after_window': 'Window Ke Baad Baarish',
      'price_rising': 'Price Badh Raha Hai',
      'price_falling': 'Price Gir Raha Hai',
      'price_advantage': 'Price Advantage',
      'transit_factor': 'Transit Factor',

      // Transit Risk
      'transit_risk': 'Transit Time Risk',
      'transit_time': 'Transit Time',
      'perishable': 'Jaldi Kharab',
      'non_perishable': 'Tikau',
      'est_spoilage': 'Est. Spoilage',
      'spoilage_risk': 'Spoilage Risk',
      'high_spoilage_warning': 'Spoilage risk zyada hai! Cold transport use karo ya paas ki mandi mein becho.',

      'loading': 'Loading...',
      'error': 'Error',
      'ok': 'OK',
      'cancel': 'Cancel',
      'refresh': 'Refresh',
    },

    // ── Marathi ────────────────────────────────────────────────────────────
    'Marathi': {
      'nav_home': 'होम',
      'nav_history': 'इतिहास',
      'nav_mandi': 'बाजार',
      'nav_profile': 'प्रोफाइल',
      'nav_godown': 'गोदाम',
      'mandi_hub': 'बाजार हब',
      'tab_prices': '📊 भाव',
      'tab_ai_chat': '🤖 AI चॅट',
      'tab_bargain': '🤝 भाव करणे',
      'chat_in': 'भाषा',
      'clear': 'साफ करा',
      'ask_placeholder': 'भाव, टिप्स, साठवणुकीबद्दल विचारा...',
      'thinking': 'विचार करत आहे...',
      'ai_assistant': 'AI बाजार सहाय्यक',
      'ai_subtitle': 'भाव, गुणवत्ता, साठवणूक,\nभाव करण्याचे टिप्स — कोणत्याही भाषेत!',
      'updated': 'अपडेट',
      'fetching': 'लोड होत आहे...',
      'items': 'वस्तू',
      'search_placeholder': '🔍 बाजार, पीक, जिल्हा शोधा...',
      'no_prices': 'भाव सापडले नाहीत',
      'retry': 'पुन्हा प्रयत्न करा',
      'fetching_prices': 'लाइव बाजारभाव लोड होत आहेत...',
      'godown_title': '🏭 स्मार्ट गोदाम',
      'godown_subtitle': 'AI पीक साठवणूक सल्लागार',
      'select_crop': 'पीक निवडा',
      'enter_crop': 'पिकाचे नाव लिहा...',
      'storage_advice': 'साठवणूक सल्ला',
      'weather_status': 'हवामान स्थिती',
      'safe_locations': 'सुरक्षित साठवणूक ठिकाणे',
      'ideal_temp': 'आदर्श तापमान',
      'ideal_humidity': 'आदर्श आर्द्रता',
      'shelf_life': 'शेल्फ लाइफ',
      'current_weather': 'सध्याचे हवामान',
      'storage_risk': 'साठवणूक जोखीम',
      'risk_low': 'कमी जोखीम ✅',
      'risk_medium': 'मध्यम जोखीम ⚠️',
      'risk_high': 'जास्त जोखीम 🔴',
      'get_advice': 'साठवणूक सल्ला घ्या',
      'loading_advice': 'हवामान व साठवणूक तपासत आहे...',
      'godown_locations': 'जवळचे गोदाम',
      'weather_crop_check': 'हवामान-पीक तपासणी',
      'crop_safe': 'साठवणुकीसाठी सुरक्षित',
      'crop_caution': 'काळजीपूर्वक साठवा',
      'crop_danger': 'साठवणुकीसाठी योग्य नाही',
      'weather': 'हवामान',
      'temperature': 'तापमान',
      'humidity': 'आर्द्रता',
      'wind': 'वारा',
      'language': 'भाषा',
      'select_language': 'भाषा निवडा',
      'settings': 'सेटिंग्ज',
      'loading': 'लोड होत आहे...',
      'error': 'चूक',
      'ok': 'ठीक',
      'cancel': 'रद्द करा',
      'refresh': 'रिफ्रेश',
    },

    // ── Tamil ──────────────────────────────────────────────────────────────
    'Tamil': {
      'nav_home': 'முகப்பு',
      'nav_history': 'வரலாறு',
      'nav_mandi': 'சந்தை',
      'nav_profile': 'சுயவிவரம்',
      'nav_godown': 'கிடங்கு',
      'mandi_hub': 'சந்தை மையம்',
      'tab_prices': '📊 விலை',
      'tab_ai_chat': '🤖 AI அரட்டை',
      'tab_bargain': '🤝 பேரம்',
      'chat_in': 'மொழி',
      'clear': 'அழி',
      'ask_placeholder': 'விலை, குறிப்பு, சேமிப்பு பற்றி கேளுங்கள்...',
      'thinking': 'யோசிக்கிறேன்...',
      'ai_assistant': 'AI சந்தை உதவியாளர்',
      'ai_subtitle': 'விலை, தரம், சேமிப்பு,\nபேரம் குறிப்புகள் — எந்த மொழியிலும்!',
      'godown_title': '🏭 ஸ்மார்ட் கிடங்கு',
      'godown_subtitle': 'AI பயிர் சேமிப்பு ஆலோசகர்',
      'select_crop': 'பயிர் தேர்வு',
      'enter_crop': 'பயிர் பெயர் உள்ளிடுக...',
      'storage_advice': 'சேமிப்பு ஆலோசனை',
      'weather_status': 'வானிலை நிலை',
      'safe_locations': 'பாதுகாப்பான சேமிப்பு இடங்கள்',
      'get_advice': 'ஆலோசனை பெறுக',
      'loading_advice': 'வானிலை & சேமிப்பு ஆய்வு...',
      'weather': 'வானிலை',
      'temperature': 'வெப்பநிலை',
      'humidity': 'ஈரப்பதம்',
      'language': 'மொழி',
      'select_language': 'மொழி தேர்வு',
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'ok': 'சரி',
      'cancel': 'ரத்து',
      'refresh': 'புதுப்பி',
    },

    // ── Telugu ──────────────────────────────────────────────────────────────
    'Telugu': {
      'nav_home': 'హోమ్',
      'nav_history': 'చరిత్ర',
      'nav_mandi': 'మార్కెట్',
      'nav_profile': 'ప్రొఫైల్',
      'nav_godown': 'గోదాం',
      'mandi_hub': 'మార్కెట్ హబ్',
      'tab_prices': '📊 ధరలు',
      'tab_ai_chat': '🤖 AI చాట్',
      'tab_bargain': '🤝 బేరం',
      'chat_in': 'భాష',
      'clear': 'క్లియర్',
      'ask_placeholder': 'ధరలు, చిట్కాలు, నిల్వ గురించి అడగండి...',
      'thinking': 'ఆలోచిస్తున్నాను...',
      'ai_assistant': 'AI మార్కెట్ సహాయకుడు',
      'godown_title': '🏭 స్మార్ట్ గోదాం',
      'select_crop': 'పంట ఎంచుకోండి',
      'storage_advice': 'నిల్వ సలహా',
      'get_advice': 'సలహా తీసుకోండి',
      'weather': 'వాతావరణం',
      'language': 'భాష',
      'select_language': 'భాష ఎంచుకోండి',
      'loading': 'లోడ్ అవుతోంది...',
    },

    // ── Bengali ─────────────────────────────────────────────────────────────
    'Bengali': {
      'nav_home': 'হোম',
      'nav_history': 'ইতিহাস',
      'nav_mandi': 'বাজার',
      'nav_profile': 'প্রোফাইল',
      'nav_godown': 'গুদাম',
      'mandi_hub': 'বাজার হাব',
      'tab_prices': '📊 দাম',
      'tab_ai_chat': '🤖 AI চ্যাট',
      'tab_bargain': '🤝 দরাদরি',
      'chat_in': 'ভাষা',
      'clear': 'মুছুন',
      'thinking': 'ভাবছি...',
      'ai_assistant': 'AI বাজার সহায়ক',
      'godown_title': '🏭 স্মার্ট গুদাম',
      'select_crop': 'ফসল বাছুন',
      'storage_advice': 'সংরক্ষণ পরামর্শ',
      'get_advice': 'পরামর্শ নিন',
      'weather': 'আবহাওয়া',
      'language': 'ভাষা',
      'select_language': 'ভাষা নির্বাচন',
      'loading': 'লোড হচ্ছে...',
    },

    // ── Kannada ─────────────────────────────────────────────────────────────
    'Kannada': {
      'nav_home': 'ಮುಖಪುಟ',
      'nav_history': 'ಇತಿಹಾಸ',
      'nav_mandi': 'ಮಾರುಕಟ್ಟೆ',
      'nav_profile': 'ಪ್ರೊಫೈಲ್',
      'nav_godown': 'ಗೋದಾಮು',
      'mandi_hub': 'ಮಾರುಕಟ್ಟೆ ಹಬ್',
      'tab_prices': '📊 ಬೆಲೆ',
      'tab_ai_chat': '🤖 AI ಚಾಟ್',
      'tab_bargain': '🤝 ಚೌಕಾಶಿ',
      'godown_title': '🏭 ಸ್ಮಾರ್ಟ್ ಗೋದಾಮು',
      'select_crop': 'ಬೆಳೆ ಆಯ್ಕೆ',
      'storage_advice': 'ಶೇಖರಣ ಸಲಹೆ',
      'get_advice': 'ಸಲಹೆ ಪಡೆಯಿರಿ',
      'weather': 'ಹವಾಮಾನ',
      'language': 'ಭಾಷೆ',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆ',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    },

    // ── Gujarati ─────────────────────────────────────────────────────────────
    'Gujarati': {
      'nav_home': 'હોમ',
      'nav_history': 'ઇતિહાસ',
      'nav_mandi': 'માર્કેટ',
      'nav_profile': 'પ્રોફાઇલ',
      'nav_godown': 'ગોદામ',
      'mandi_hub': 'માર્કેટ હબ',
      'tab_prices': '📊 ભાવ',
      'tab_ai_chat': '🤖 AI ચેટ',
      'tab_bargain': '🤝 ભાવતાલ',
      'godown_title': '🏭 સ્માર્ટ ગોદામ',
      'select_crop': 'પાક પસંદ કરો',
      'storage_advice': 'સંગ્રહ સલાહ',
      'get_advice': 'સલાહ મેળવો',
      'weather': 'હવામાન',
      'language': 'ભાષા',
      'select_language': 'ભાષા પસંદ કરો',
      'loading': 'લોડ થઈ રહ્યું...',
    },

    // ── Punjabi ──────────────────────────────────────────────────────────────
    'Punjabi': {
      'nav_home': 'ਹੋਮ',
      'nav_history': 'ਇਤਿਹਾਸ',
      'nav_mandi': 'ਮੰਡੀ',
      'nav_profile': 'ਪ੍ਰੋਫਾਈਲ',
      'nav_godown': 'ਗੋਦਾਮ',
      'mandi_hub': 'ਮੰਡੀ ਹੱਬ',
      'tab_prices': '📊 ਭਾਅ',
      'tab_ai_chat': '🤖 AI ਚੈਟ',
      'tab_bargain': '🤝 ਮੋਲ-ਭਾਅ',
      'godown_title': '🏭 ਸਮਾਰਟ ਗੋਦਾਮ',
      'select_crop': 'ਫ਼ਸਲ ਚੁਣੋ',
      'storage_advice': 'ਸਟੋਰੇਜ ਸਲਾਹ',
      'get_advice': 'ਸਲਾਹ ਲਵੋ',
      'weather': 'ਮੌਸਮ',
      'language': 'ਭਾਸ਼ਾ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ...',
    },
  };
}
